### PR TITLE
Adding support to older android versions.

### PR DESCRIPTION
**Pull request by cloneconf**
Notz looks like it work on api 17 (android 4.2).

I did some testing on android 4.2 and it did work :)
Here a video: https://youtu.be/F6egvtiIwyw

I should note that things could go wrong when using on older version of android,
but at least you get more audience by lowering api requirements.

Best Regards.

### CODE REVIEW

**Comment by sunilpaulmathew** [comment]
@cloneconf 
Thanks a lot for your work. Everything (including the video) looks good. However, I have some un-pushed commits in my local repo, so that I can't right away merge this. Also, I like to get more feedbacks from users in my telegram group (I hope there will be more uses on Android < 6). If everything okay, I'll merge this (or manually pick this with full credits to you) soon.
Just a quick question: Is using _srcCompat_, instead of _src_ will make any big difference? Jsut asking to know.
Once again, thanks. alot for your contribution.

**Comment by cloneconf** [comment]
I am happy to help :)

> Is using srcCompat, instead of src will make any big difference?

It crashes without it on older versions.


This seems required on older versions when you use vector drawable as the javadoc says.
```
Sets a drawable as the content of this ImageView.
Allows the use of vector drawable when running on older versions of the platform.
```

**Comment by cloneconf** [comment]
> I have some un-pushed commits in my local repo, so that I can't right away merge this.
If did add some new vector images you should use **app:srcCompat**.

**Comment by sunilpaulmathew** [comment]
> 
> 
> > I have some un-pushed commits in my local repo, so that I can't right away merge this.
> 
> If you did add some new vector images you should use **app:srcCompat**.

Ok, I'll take care of it. Once again, thanks a lot.

**Comment by sunilpaulmathew** [comment]
@cloneconf 
PR is merged almost as such. One main thing I removed is the if statement to check SDK VERSION_CODES (getColoredDrawable method) from 4a2ab2383ff5862d51455727c0031501823c4fe0 as we used it on only two places, but specific for Android O and higher. Everything looks great and now waiting for the user feedback. Btw, thanks for the Arabic translations.

**Comment by sunilpaulmathew** [comment]
Hi @cloneconf 
I managed to fix a series of issues (related with widgets, backup/restore etc.) on API 17. However, even after [this](b7748dc4b372765070b93150fdfd0b334bbbf10b) commit, the reminders seems half broken. It will be great if you have a look on this when you have time. I'm a bit handicapped here due to the lack of a real device.
Thanks a lot in advance

**Comment by cloneconf** [comment]
> Hi @cloneconf I managed to fix a series of issues (related with widgets, backup/restore etc.) on API 17. However, even after [this](https://github.com/sunilpaulmathew/sNotz/commit/b7748dc4b372765070b93150fdfd0b334bbbf10b) commit, the reminders seems half broken. It will be great if you have a look on this when you have time. I'm a bit handicapped here due to the lack of a real device. Thanks a lot in advance

I really don't know how `AlarmManager` works, cuz i didn't use it before !

**Comment by sunilpaulmathew** [comment]
> I really don't know how `AlarmManager` works, cuz i didn't use it before !

No Problem. Its almost functional. In the worst case, I will hide it on below KitKat :)

**Pull request merged**
